name : "Test Workflow"
on : [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1
      - name: Checkout code
        uses: actions/checkout@v2
      # 2
      - name: Generate Release APK
        run: ./gradlew assembleRelease
      # 3
#      - name: Sign APK
#        uses: r0adkll/sign-android-release@v1
#        # ID used to access action output
#        id: sign_app
#        with:
#          releaseDirectory: app/build/outputs/apk/release
#          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
#          alias: ${{ secrets.ALIAS }}
#          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
#          keyPassword: ${{ secrets.KEY_PASSWORD }}
      # 4
      - uses: actions/upload-artifact@master
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.txt
      # 5
      - uses: actions/upload-artifact@master
        with:
          name: mapping.txt
          path: app/build/outputs/mapping/release/mapping.txt

#jobs:
#  build:
#    name: "Build project"
#    runs-on: ubuntu-latest
#    steps:
#      - name: "Checkout current repository in ubuntu file system"
#        user: actions/checkout@v1
#      - name: "Setup JDK 1.8"
#        uses: actions/setup-java@v1
#        - name: "Builds debug build"
#          run: /gradlew assembleDebug
          